#!/bin/bash

#show in the form 201608121900 which is YYYYMMDDhhmm
sShow=$(tr -d -c '[:digit:]' <<< "${1}")
[[ ${#sShow} -eq 12 ]] || exit 1

sType="mp3"
sMType="mpeg"
sMedia="/srv/static/shows"  # changed

#/var/www/web1/storage/ShowArchive/
sFile=$(ls -1 ${sMedia}/${sShow}*.${sType})


sMIME="audio/${sMType}"

if [[ -f "${sFile}" ]]; then
  sCopyRange=""
  sSize=$(stat --printf="%s" "${sFile}")
  if [[ ! -z "${HTTP_RANGE-}" ]]
  then
    sRange=${HTTP_RANGE%=*}
    sValue=${HTTP_RANGE#*=}
    sVL=${sValue%-*}
    sVH=${sValue#*-}
    [[ -z ${sVH} ]] && sVH=$(( sSize - 1 ))
    if [[ "${sRange}" = "bytes" ]] && [[ ${sVL} -lt ${sSize} ]] && \
	 [[ ${sVL} -lt ${sVH} ]] && [[ ${sVH} -le ${sSize} ]]
    then
	sCopyRange="iflag=skip_bytes,count_bytes skip=${sVL} count=$((sVH-sVL+1))" 
#	sCopyRange="ibs=1 skip=${sVL} count=$((sVH-sVL+1))" 
    fi  
    [[ ${HTTP_RANGE} = "bytes=0-" ]] && sCopyRange=""
  fi
  echo "Access-Control-Allow-Origin: *"
  echo "Content-Type: ${sMIME}"
  echo "Date: $(date -R)"
  sLM=$(stat --printf="%y" "${sFile}")
  echo "Last-Modified: ${sLM}"
  sName=$(basename "${sFile}")
  echo "ETag: \"${sName}\""
#  echo "Content-Disposition: filename=\"$(basename ${sFile})\""
#  echo "Content-Transfer-Encoding: binary"
  echo "Accept-Ranges: bytes"
  if [[ -z ${sCopyRange} ]]; then
    echo "Content-Length: ${sSize}"
  else
    echo "Status: 206 Partial Content"
    echo "Expires: $(date -R -d tomorrow)"
    echo "Content-Length: $((sVH-sVL+1))"
    echo "Content-Range: bytes ${sVL}-${sVH}/${sSize}"
  fi
  echo ""
  dd if="${sFile}" ${sCopyRange} 
fi
