#!/bin/bash
#install to cgi-bin for httpd /usr/local/cgi-bin/web80/
#ptaffs April 2014. wrir.org 97.3lpfm RVA

sDB="$(ls /srv/static/*.lsdb|tail -1)"  # same dir as html error page

sFilter="|"

if [[ "${1}" == "Band" ]]
then
  if cut -f2 -d'|' ${sDB} | grep -q -e "^${2}$" 
  then
    sFilter="|${2}|"
  fi
fi

if [[ "${1}" == "Genre" ]]
then
  cut -f11 -d'|' ${sDB} | tr ';' '\n' | grep -q -e "^${2}$" && sFilter="${2}"
fi

if [[ "${1}" == "Show" ]]
then
  cut -f5 -d'|' ${sDB} | grep -q -e "^${2}$" && sFilter="|${2}|"
fi

sDBN="${sDB##*/}"
sDB2="${sDBN%.lsdb}"

sFirst=0
echo "Content-type: application/json"
echo "Access-Control-Allow-Origin: *"
echo
echo "["
sort -k2,2 -k5,5 -k3,3n  -t'|' ${sDB} | grep -e "${sFilter}" |
while IFS=\| read sID sArt sTrk sTtl sSet sFol sFil sYr sDy sFTS sGenre sFiller
do
  [[ ${sFirst} = 1 ]] && echo ","
  sFirst=1
  echo "{\"Artist\": \"${sArt/\"/\\\"}\","
  echo "\"TrackNo\": \"${sTrk}\","
  echo "\"Title\": \"${sTtl/\"/\\\"}\","
# echo "\"Set\": \"${sSet}-${sYr}\","
  echo "\"Show\": \"${sSet/\"/\\\"}\","
  echo "\"Date\": \"${sYr}\","
  echo "\"FileTime\": \"${sFTS}\","
#  echo "\"Folder\": \"${sFol}\","
  echo "\"Genre\": \"${sGenre}\","
  echo "\"sDBver\": \"${sDB2}\","
  echo "\"sTkid\": \"${sID}\"}"
done
echo "]"
