version: '3.8'

services:
  files.wrir.org:
    image: httpd
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - ./json/htdocs:/var/local/apache2/htdocs
      - ./json/cgi-bin:/var/local/apache2/cgi-bin
      - ./json/httpd.conf:/var/local/apache2/conf/httpd.conf
      - ./stream-recorder/publish:/var/local/apache2/htdocs/shows
    restart: always
    
  icecast:
    image: infiniteproject/icecast
    enviornment:
      ICECAST_SOURCE_PASSWORD: wwr4trou
      ICECAST_ADMIN_PASSWORD: wwr4trou
      ICECAST_RELAY_PASSWORD: wwr4trou
      ICECAST_ADMIN_USERNAME: wrirops
      ICECAST_ADMIN_EMAIL: operations@wrir.org
      ICECAST_LOCATION: Richmond, VA
      ICECAST_HOSTNAME: bandito
      ICECAST_MAX_CLIENTS: 50
      ICECAST_MAX_SOURCES: 2
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    restart: always
    
  stream-recorder:
    build: stream-recorder/.
    volumes:
      - ./stream-recorder/scripts:/scripts
    depends_on:
      - icecast
    restart: always
