FROM httpd
MAINTAINER Zachary Klosko (kloskoz@vcu.edu)

# Mount network shares
COPY smbcreds /
RUN apt update -y && apt install cifs-utils -y && \
mount -t cifs -o credentials=/smbcreds 192.168.200.16/shared /shares/Y && \
mount -t cifs -o credentials=/smbcreds 192.168.200.23/z /shares/Z

COPY cgi-bin/ # /usr/local/cgi-bin/web80/
COPY apache2.conf /etc/apache2

RUN a2enmod cgid && systemctl httpd restart

EXPOSE 80
CMD ["httpd-foreground"]