#!/bin/bash
#install to cgi-bin for httpd /usr/local/cgi-bin/web80/showlist
#ptaffs April 2014. wrir.org 97.3lpfm RVA
#json version

sMediaPath=/recorder/publish  # was /var/www/web1/storage/ShowArchive/
sFirst=0

sType="all"

[[ "${1}" == "music" ]] && sType="music"
[[ "${1}" == "local" ]] && sType="local"
if [[ "${1:0:2}" == "20" ]] && [[ ${#1} -eq 12 ]]
then
  sOnlyShow="${1}"
  sMTime=""
else
  sOnlyShow=""
  sMTime="-mtime -14"
fi

echo "Content-type: application/json"
echo "Access-Control-Allow-Origin: *"
echo
echo "["
find ${sMediaPath}/${sOnlyShow}*.ready ${sMTime}|sort -r|
while read sFile
do
  
  sBaseName=${sFile##*/}
  sShow=${sBaseName:13:99}
  sShow=${sShow%%.ready}

  if [[ -f ${sFile%%.ready}.info ]]; then
    sInfo=$(tr -d '"' <${sFile%%.ready}.info)
    IFS='|' read sF1 sDa sShow sDJ sSD <<< "${sInfo}"
  else
    unset sF1 sDa sDJ sSD
  fi

  sData=$(grep -i "|${sShow}|" ${sMediaPath}/showdata.txt|head -1)
  [[ -z "${sData}" ]]  && sData="||${sShow}|${sShow}||||||||"
  sUXTime=$(date -d "${sBaseName:0:4}/${sBaseName:4:2}/${sBaseName:6:2} ${sBaseName:8:2}:${sBaseName:10:2}")

  IFS='|' read -a sShowData <<< "${sData}"
  
  if [[ "${sType}" == "all" ]] || [[ "${sType}" == "${sShowData[4]}" ]]
  then
      [[ ${sFirst} = 1 ]] && echo ","
      sFirst=1
      echo "{\"title\": \"${sShowData[3]}\","
      echo "\"show\": \"${sSD}\","
      echo "\"presenter\": \"${sDJ}\","
      echo "\"presenter2\": \"${sDJ}\","
      echo "\"datestamp\": \"${sBaseName:0:12}\","
      echo "\"dateunix\": \"${sUXTime}\","
      echo "\"mp3\": \"http://files.wrir.org/shows/${sBaseName%%.ready}.mp3\","
      echo "\"oga\": \"http://files.wrir.org/shows/${sBaseName%%.ready}.ogg\","
      echo "\"type\": \"${sShowData[4]}\","
      sPoster=${sShowData[7]%%*/}
      echo "\"poster\": \"${sShowData[7]}\","
      echo "\"poster2\": \"${sShowData[7]}\","
      echo "\"showurl\": \"${sShowData[6]}\"}"
    fi
done
echo "]"
