FROM alpine:latest
MAINTAINER Zachary Klosko (kloskoz@vcu.edu)

# Install cron
RUN apk update && apk add wget bash

# Add files
COPY hourly /etc/periodic/hourly
COPY weekly /etc/periodic/weekly
COPY monthly /etc/periodic/monthly

VOLUME ["/etc/periodic/hourly", "/etc/periodic/weekly", "/etc/periodic/monthly"]

CMD crond -f