FROM debian:stretch-slim
MAINTAINER from Neha Bhardwaj, extended by Zachary Klosko (kloskoz@vcu.edu)

# Install cron
RUN apt update -y && apt install -y cron

# Add files
ADD scripts /scripts
ADD entrypoint.sh /entrypoint.sh
 
RUN chmod +x /entrypoint.sh

ENTRYPOINT /entrypoint.sh