#!/bin/bash

sWorking="/var/local/wrir-monitoring/"

echo "Content-type: text/html"
echo ''

if [[ "${REMOTE_ADDR%.*}" == "192.168.200" ]] || [[ "${REMOTE_ADDR%.*}" == "127.0.0" ]]
then
  mkdir -p ${sWorking}/${REMOTE_ADDR}
  touch ${sWorking}/${REMOTE_ADDR}/checkin
#  cat > ${sWorking}/${REMOTE_ADDR}/data.txt
  echo "Thank you ${REMOTE_ADDR}"
fi
