#!/bin/bash
#install to cgi-bin for httpd /usr/local/cgi-bin/web80/
#ptaffs April 2014. wrir.org 97.3lpfm RVA

sDB=$(ls /usr/local/apache2/htdocs/*.lsdb|tail -1)

sFirst=0
echo "Content-type: application/json"
echo "Access-Control-Allow-Origin: *"
echo
echo "["

sDBN=${sDB##*/}
sDB2=${sDBN%.lsdb}
cut -f2 -d\| ${sDB}|sort -u|
while IFS=\| read sArt
do
  [[ ${sFirst} = 1 ]] && echo ","
  sFirst=1
  echo "{\"Artist\": \"${sArt}\"}"
done
echo "]"
