FROM httpd
MAINTAINER Zachary Klosko (kloskoz@vcu.edu)

# Mount network shares
COPY smbcreds /creds
RUN apt update -y && apt install cifs-utils -y && \
mount -t cifs -o credentials=/creds/smbcreds 192.168.200.16/shared /shares/Y && \
mount -t cifs -o credentials=/creds/smbcreds 192.168.200.23/z /shares/Z

COPY apache2 /usr/local/apache2

VOLUME ["/usr/local/apache2", "/shares"]

EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["httpd-foreground"]