FROM httpd
MAINTAINER Zachary Klosko (kloskoz@vcu.edu)

COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY htdocs /usr/local/apache2/htdocs
COPY cgi-bin /usr/local/apache2/cgi-bin

VOLUME /usr/local/apache2

EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["httpd-foreground"]