FROM ubuntu:16.04
MAINTAINER Zachary Klosko (kloskoz@vcu.edu)

RUN apt update -y && apt install nginx-full -y

COPY nginx-conf /etc/nginx
COPY storage /var/www

EXPOSE 443
STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"]