#!/bin/bash
#install to cgi-bin for httpd /usr/local/cgi-bin/web80/
#ptaffs April 2014. wrir.org 97.3lpfm RVA

echo "Content-type: application/json"
echo "Access-Control-Allow-Origin: *"
echo
echo "[{Beat}]"
