FROM httpd
MAINTAINER Zachary Klosko (kloskoz@vcu.edu)

COPY httpd.conf /usr/local/apache2/conf/httpd.conf
ADD cgi-bin /srv/cgi-bin

VOLUME /usr/local/apache2
VOLUME /srv

EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["httpd-foreground"]